### ISSUE TITLE
LIBUSB error when multiple Balena Fins are connected at the same time

### ISSUE THREAD

**Issue by imrehg** [balena-io/etcher#2461]
Starting etcher with root privileges, plugging in Balena Fins for flashing. When one device is still in an initializing state, and I connect another one (so to initialize them in parallel), I got this error popup:

![screenshot_2018-08-31_00-13-22](https://user-images.githubusercontent.com/38863/44912384-de4e4e80-ad21-11e8-91d4-6d58b1e98216.png)

Also, the initialization doesn't seem to finish after this warning.

- **Etcher version:** 1.4.4
- **Operating system and architecture:** ArchLinux 64-bit
- **Image flashed:** before any image selection
- **Do you see any meaningful error information in the DevTools?** 

The same stack trace is there:

```
gui.js:sourcemap:114128 {"stack":"Error: LIBUSB_ERROR_IO\n    at Device.usb.Device.open (/usr/share/etcher/node_modules/usb/usb.js:33:7)\n    at Bluebird.try (/usr/share/etcher/lib/sdk/adapters/usbboot/index.js:379:14)\n    at tryCatcher (/usr/share/etcher/node_modules/bluebird/js/release/util.js:16:23)\n    at Function.Promise.attempt.Promise.try (/usr/share/etcher/node_modules/bluebird/js/release/method.js:39:29)\n    at USBBootAdapter.prepare (/usr/share/etcher/lib/sdk/adapters/usbboot/index.js:376:24)\n    at usb.listDevices.filter.map (/usr/share/etcher/lib/sdk/adapters/usbboot/index.js:304:14)\n    at tryCatcher (/usr/share/etcher/node_modules/bluebird/js/release/util.js:16:23)\n    at MappingPromiseArray._promiseFulfilled (/usr/share/etcher/node_modules/bluebird/js/release/map.js:57:38)\n    at MappingPromiseArray.PromiseArray._iterate (/usr/share/etcher/node_modules/bluebird/js/release/promise_array.js:113:31)\n    at MappingPromiseArray.init (/usr/share/etcher/node_modules/bluebird/js/release/promise_array.js:77:10)\n    at new MappingPromiseArray (/usr/share/etcher/node_modules/bluebird/js/release/map.js:25:10)\n    at map (/usr/share/etcher/node_modules/bluebird/js/release/map.js:152:12)\n    at Promise.map (/usr/share/etcher/node_modules/bluebird/js/release/map.js:156:12)\n    at USBBootAdapter.scan (/usr/share/etcher/lib/sdk/adapters/usbboot/index.js:260:57)\n    at runScan (/usr/share/etcher/lib/sdk/scanner.js:131:17)","message":"LIBUSB_ERROR_IO","errno":-1}
```

If I plug in the devices serially, ie. the second after the first one finished initializing, then it all works.

**Comment by thundron** [comment]
Fixed in 1.4.7
