### ISSUE TITLE
Burning image does not start

### ISSUE THREAD

**Issue by gitowiec** [balena-io/etcher#2836]
- **Etcher version:**  balena-etcher-electron-1.5.50-linux-x64.zip
- **Operating system and architecture:**  Ubuntu Budgie 18.04 AMD64
- **Image flashed:** raw image created from qemu/kvm
- **Do you see any meaningful error information in the DevTools?**
````
cause : Error: User did not grant permission. at /tmp/.mount_balenaNblKgE/resources/app.asar/node_modules/sudo-prompt/index.js:111:23 at ChildProcess.exithandler (child_process.js:310:5) at ChildProcess.emit (events.js:182:13) at maybeClose (internal/child_process.js:961:16) at Socket.stream.socket.on (internal/child_process.js:380:11) at Socket.emit (events.js:182:13) at Pipe._handle.close [as _onclose] (net.js:596:12)
message : "User did not grant permission."
stack:"Error: User did not grant permission.↵    at /tmp/.mount_balenaNblKgE/resources/app.asar/node_modules/sudo-prompt/index.js:111:23↵    at ChildProcess.exithandler (child_process.js:310:5)↵    at ChildProcess.emit (events.js:182:13)↵    at maybeClose (internal/child_process.js:961:16)↵    at Socket.stream.socket.on (internal/child_process.js:380:11)↵    at Socket.emit (events.js:182:13)↵    at Pipe._handle.close [as _onclose] (net.js:596:12)"
__proto__:Object
isOperational:true
message:"User did not grant permission."
name:"Error"
stack:"Error: User did not grant permission.↵    at /tmp/.mount_balenaNblKgE/resources/app.asar/node_modules/sudo-prompt/index.js:111:23↵    at ChildProcess.exithandler (child_process.js:310:5)↵    at ChildProcess.emit (events.js:182:13)↵    at maybeClose (internal/child_process.js:961:16)↵    at Socket.stream.socket.on (internal/child_process.js:380:11)↵    at Socket.emit (events.js:182:13)↵    at Pipe._handle.close [as _onclose] (net.js:596:12)"
__proto__:Error
````

Nothing happens:

![Peek 2019-06-26 11-57](https://user-images.githubusercontent.com/1553195/60170910-b88eba80-9809-11e9-8b46-591de2115404.gif)

**Comment by nathfreder** [comment]
This seems similar to #2833
