### ISSUE TITLE
Unable to flash in Ubuntu 18.04.4 !

### ISSUE THREAD

**Issue by vincegre** [balena-io/etcher#3121]
Each time I try to flash an img file to SD card, it complains straight after typing my password that it failed !

- Etcher version: 1.5.80 (64 bits AppImage)1
- Operating system and architecture: Ubuntu 18.04.4 64 bits (amd64)
- Image flashed: tried multiple differents img file (checked with checksum so I'm sure img file are good)
- Do you see any meaningful error information in the DevTools?

here is copy/paste of what is displayed in DevTools:

```
/tmp/.mount_balenauaUnvm/resources/app.asar/node_modules/raven-js/dist/raven.js:58 {"stack":"Error: The elevated process died unexpectedly\n    at createError (file:///tmp/.mount_balenauaUnvm/resources/app.asar/generated/gui.js:1092:19)\n    at Object.createUserError (file:///tmp/.mount_balenauaUnvm/resources/app.asar/generated/gui.js:1113:12)\n    at file:///tmp/.mount_balenauaUnvm/resources/app.asar/generated/gui.js:5882:30","message":"The elevated process died unexpectedly","description":"The process error code was 126","report":false,"image":"respeaker-debian-9-iot-flasher-20180801-4gb.img"}

  | console.<computed> | @ | /tmp/.mount_balenaua…js/dist/raven.js:58
-- | -- | -- | --
  | logException | @ | /tmp/.mount_balenaua…resin-corvus.js:233
  | flashImageToDrive | @ | gui.js:5167
  | async function (async) |   |  
  | flashImageToDrive | @ | gui.js:5151
  | tryFlash | @ | gui.js:5245
  | callCallback | @ | /tmp/.mount_balenaua….development.js:336
  | wrapped | @ | /tmp/.mount_balenaua…s/dist/raven.js:444
  | invokeGuardedCallbackDev | @ | /tmp/.mount_balenaua….development.js:385
  | invokeGuardedCallback | @ | /tmp/.mount_balenaua….development.js:440
  | invokeGuardedCallbackAndCatchFirstError | @ | /tmp/.mount_balenaua….development.js:454
  | executeDispatch | @ | /tmp/.mount_balenaua….development.js:584
  | executeDispatchesInOrder | @ | /tmp/.mount_balenaua….development.js:609
  | executeDispatchesAndRelease | @ | /tmp/.mount_balenaua….development.js:713
  | executeDispatchesAndReleaseTopLevel | @ | /tmp/.mount_balenaua….development.js:722
  | forEachAccumulated | @ | /tmp/.mount_balenaua….development.js:694
  | runEventsInBatch | @ | /tmp/.mount_balenaua….development.js:739
  | runExtractedPluginEventsInBatch | @ | /tmp/.mount_balenaua….development.js:880
  | handleTopLevel | @ | /tmp/.mount_balenaua…development.js:5807
  | batchedEventUpdates$1 | @ | /tmp/.mount_balenaua…evelopment.js:24368
  | batchedEventUpdates | @ | /tmp/.mount_balenaua…development.js:1419
  | dispatchEventForPluginEventSystem | @ | /tmp/.mount_balenaua…development.js:5898
  | attemptToDispatchEvent | @ | /tmp/.mount_balenaua…development.js:6014
  | dispatchEvent | @ | /tmp/.mount_balenaua…development.js:5918
  | unstable_runWithPriority | @ | /tmp/.mount_balenaua….development.js:818
  | runWithPriority$2 | @ | /tmp/.mount_balenaua…evelopment.js:12130
  | discreteUpdates$1 | @ | /tmp/.mount_balenaua…evelopment.js:24384
  | discreteUpdates | @ | /tmp/.mount_balenaua…development.js:1442
  | dispatchDiscreteEvent | @ | /tmp/.mount_balenaua…development.js:5885
  | wrapped | @ | /tmp/.mount_balenaua…s/dist/raven.js:444

```

**Comment by lurch** [comment]
Dunno if it helps, but "The process error code was 126" from your log above also appears in #2859
