### ISSUE TITLE
make electron-build fails with Exit code: 1. Command failed: node-gyp rebuild

### ISSUE THREAD

**Issue by gantonayde** [balena-io/etcher#3152]
Hello, I have cloned 869d875b and tried to pack a .deb file, however `make electron-build` keeps giving me the following error:

>  • executing node-gyp rebuild  arch=x64
>   ⨯ Exit code: 1. Command failed: node-gyp rebuild
>   stackTrace=
>                                                                            Error: Exit code: 1. Command failed: node-gyp rebuild
>                                                                            
>                                                                                at /home/user/Desktop/github/etcher/node_modules/builder-util/src/util.ts:129:16
>                                                                                at ChildProcess.exithandler (child_process.js:306:5)
>                                                                                at ChildProcess.emit (events.js:193:13)
>                                                                                at maybeClose (internal/child_process.js:999:16)
>                                                                                at Process.ChildProcess._handle.onexit (internal/child_process.js:266:5)
> 

I am running Ubuntu 20.04, `make electron-develop` and `npm start` work without a problem. What am I doing wrong?

**Comment by gantonayde** [comment]
Nodejs and npm were installed as snaps, installing them from apt solved the issue
