### ISSUE TITLE
Blank Etcher Screen on Windows

### ISSUE THREAD

**Issue by williamclavier** [balena-io/etcher#3163]
- 1.5.90
- Windows 10 x64
- No image

Fresh install of Windows 10 and I installed etcher and only got a blank screen.

```
Uncaught TypeError: Cannot read property 'path' of undefined
    at isSourceDrive (gui.js:1730)
    at Object.getDriveImageCompatibilityStatuses (gui.js:1822)
    at DriveCompatibilityWarning (gui.js:5060)
    at renderWithHooks (C:\Users\wcinv\AppData\Local\Programs\balena-etcher\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:14803)
    at mountIndeterminateComponent (C:\Users\wcinv\AppData\Local\Programs\balena-etcher\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:17482)
    at beginWork (C:\Users\wcinv\AppData\Local\Programs\balena-etcher\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:18596)
    at HTMLUnknownElement.callCallback (C:\Users\wcinv\AppData\Local\Programs\balena-etcher\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:188)
    at HTMLUnknownElement.wrapped (C:\Users\wcinv\AppData\Local\Programs\balena-etcher\resources\app.asar\node_modules\raven-js\dist\raven.js:444)
    at Object.invokeGuardedCallbackDev (C:\Users\wcinv\AppData\Local\Programs\balena-etcher\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:237)
    at invokeGuardedCallback (C:\Users\wcinv\AppData\Local\Programs\balena-etcher\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:292)
    at beginWork$1 (C:\Users\wcinv\AppData\Local\Programs\balena-etcher\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:23203)
    at performUnitOfWork (C:\Users\wcinv\AppData\Local\Programs\balena-etcher\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:22154)
    at workLoopSync (C:\Users\wcinv\AppData\Local\Programs\balena-etcher\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:22130)
    at performSyncWorkOnRoot (C:\Users\wcinv\AppData\Local\Programs\balena-etcher\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:21756)
    at C:\Users\wcinv\AppData\Local\Programs\balena-etcher\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:11089
    at unstable_runWithPriority (C:\Users\wcinv\AppData\Local\Programs\balena-etcher\resources\app.asar\node_modules\scheduler\cjs\scheduler.development.js:653)
    at runWithPriority$1 (C:\Users\wcinv\AppData\Local\Programs\balena-etcher\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:11039)
    at flushSyncCallbackQueueImpl (C:\Users\wcinv\AppData\Local\Programs\balena-etcher\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:11084)
    at flushSyncCallbackQueue (C:\Users\wcinv\AppData\Local\Programs\balena-etcher\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:11072)
    at scheduleUpdateOnFiber (C:\Users\wcinv\AppData\Local\Programs\balena-etcher\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:21199)
    at Object.enqueueSetState (C:\Users\wcinv\AppData\Local\Programs\balena-etcher\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:12639)
    at MainPage.Component.setState (C:\Users\wcinv\AppData\Local\Programs\balena-etcher\resources\app.asar\node_modules\react\cjs\react.development.js:471)
    at gui.js:3898
    at changeHandler (gui.js:785)
    at Object.dispatch (C:\Users\wcinv\AppData\Local\Programs\balena-etcher\resources\app.asar\node_modules\redux\lib\redux.js:228)
    at Object.setDrives (gui.js:2182)
    at setDrives (gui.js:3439)
    at Scanner.addDrive (gui.js:3451)
isSourceDrive @ gui.js:1730
getDriveImageCompatibilityStatuses @ gui.js:1822
DriveCompatibilityWarning @ gui.js:5060
renderWithHooks @ C:\Users\wcinv\AppData\Local\Programs\balena-etcher\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:14803
mountIndeterminateComponent @ C:\Users\wcinv\AppData\Local\Programs\balena-etcher\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:17482
beginWork @ C:\Users\wcinv\AppData\Local\Programs\balena-etcher\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:18596
callCallback @ C:\Users\wcinv\AppData\Local\Programs\balena-etcher\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:188
wrapped @ C:\Users\wcinv\AppData\Local\Programs\balena-etcher\resources\app.asar\node_modules\raven-js\dist\raven.js:444
invokeGuardedCallbackDev @ C:\Users\wcinv\AppData\Local\Programs\balena-etcher\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:237
invokeGuardedCallback @ C:\Users\wcinv\AppData\Local\Programs\balena-etcher\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:292
beginWork$1 @ C:\Users\wcinv\AppData\Local\Programs\balena-etcher\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:23203
performUnitOfWork @ C:\Users\wcinv\AppData\Local\Programs\balena-etcher\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:22154
workLoopSync @ C:\Users\wcinv\AppData\Local\Programs\balena-etcher\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:22130
performSyncWorkOnRoot @ C:\Users\wcinv\AppData\Local\Programs\balena-etcher\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:21756
(anonymous) @ C:\Users\wcinv\AppData\Local\Programs\balena-etcher\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:11089
unstable_runWithPriority @ C:\Users\wcinv\AppData\Local\Programs\balena-etcher\resources\app.asar\node_modules\scheduler\cjs\scheduler.development.js:653
runWithPriority$1 @ C:\Users\wcinv\AppData\Local\Programs\balena-etcher\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:11039
flushSyncCallbackQueueImpl @ C:\Users\wcinv\AppData\Local\Programs\balena-etcher\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:11084
flushSyncCallbackQueue @ C:\Users\wcinv\AppData\Local\Programs\balena-etcher\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:11072
scheduleUpdateOnFiber @ C:\Users\wcinv\AppData\Local\Programs\balena-etcher\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:21199
enqueueSetState @ C:\Users\wcinv\AppData\Local\Programs\balena-etcher\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:12639
Component.setState @ C:\Users\wcinv\AppData\Local\Programs\balena-etcher\resources\app.asar\node_modules\react\cjs\react.development.js:471
(anonymous) @ gui.js:3898
changeHandler @ gui.js:785
dispatch @ C:\Users\wcinv\AppData\Local\Programs\balena-etcher\resources\app.asar\node_modules\redux\lib\redux.js:228
setDrives @ gui.js:2182
setDrives @ gui.js:3439
addDrive @ gui.js:3451
async function (async)
addDrive @ gui.js:3446
emit @ events.js:203
onAttach @ C:\Users\wcinv\AppData\Local\Programs\balena-etcher\resources\app.asar\node_modules\etcher-sdk\build\scanner\scanner.js:34
emit @ events.js:203
scan @ C:\Users\wcinv\AppData\Local\Programs\balena-etcher\resources\app.asar\node_modules\etcher-sdk\build\scanner\adapters\block-device.js:94
async function (async)
scan @ C:\Users\wcinv\AppData\Local\Programs\balena-etcher\resources\app.asar\node_modules\etcher-sdk\build\scanner\adapters\block-device.js:77
scanLoop @ C:\Users\wcinv\AppData\Local\Programs\balena-etcher\resources\app.asar\node_modules\etcher-sdk\build\scanner\adapters\block-device.js:68
start @ C:\Users\wcinv\AppData\Local\Programs\balena-etcher\resources\app.asar\node_modules\etcher-sdk\build\scanner\adapters\block-device.js:59
(anonymous) @ C:\Users\wcinv\AppData\Local\Programs\balena-etcher\resources\app.asar\node_modules\etcher-sdk\build\scanner\scanner.js:59
(anonymous) @ C:\Users\wcinv\AppData\Local\Programs\balena-etcher\resources\app.asar\node_modules\etcher-sdk\build\scanner\scanner.js:51
start @ C:\Users\wcinv\AppData\Local\Programs\balena-etcher\resources\app.asar\node_modules\etcher-sdk\build\scanner\scanner.js:50
(anonymous) @ gui.js:3478
__webpack_require__ @ gui.js:21
(anonymous) @ gui.js:85
(anonymous) @ gui.js:88
C:\Users\wcinv\AppData\Local\Programs\balena-etcher\resources\app.asar\node_modules\raven-js\dist\raven.js:58 The above error occurred in the <DriveCompatibilityWarning> component:
    in DriveCompatibilityWarning (created by TargetSelector)
    in p (created by styled.div)
    in styled.div
    in Unknown (created by ForwardRef)
    in ForwardRef (created by Component)
    in Component (created by ForwardRef)
    in ForwardRef (created by ForwardRef)
    in ForwardRef (created by WithTheme(Component))
    in WithTheme(Component) (created by Styled(WithTheme(Component)))
    in Styled(WithTheme(Component)) (created by TargetSelector)
    in TargetSelector
    in div
    in div
    in Unknown (created by MainPage)
    in div (created by MainPage)
    in div (created by styled.div)
    in styled.div (created by ForwardRef)
    in ForwardRef (created by Component)
    in Component (created by ForwardRef)
    in ForwardRef (created by ForwardRef)
    in ForwardRef (created by Box)
    in Box (created by Flex)
    in Flex (created by MainPage)
    in div (created by StyledGrommet)
    in StyledGrommet (created by Grommet)
    in Grommet (created by Styled(Grommet))
    in Styled(Grommet) (created by Provider)
    in BreakpointProvider (created by Provider)
    in Provider
    in Unknown (created by MainPage)
    in MainPage

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries.
console.<computed> @ C:\Users\wcinv\AppData\Local\Programs\balena-etcher\resources\app.asar\node_modules\raven-js\dist\raven.js:58
logCapturedError @ C:\Users\wcinv\AppData\Local\Programs\balena-etcher\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:19527
logError @ C:\Users\wcinv\AppData\Local\Programs\balena-etcher\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:19564
update.callback @ C:\Users\wcinv\AppData\Local\Programs\balena-etcher\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:20708
callCallback @ C:\Users\wcinv\AppData\Local\Programs\balena-etcher\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:12490
commitUpdateQueue @ C:\Users\wcinv\AppData\Local\Programs\balena-etcher\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:12511
commitLifeCycles @ C:\Users\wcinv\AppData\Local\Programs\balena-etcher\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:19883
commitLayoutEffects @ C:\Users\wcinv\AppData\Local\Programs\balena-etcher\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:22803
callCallback @ C:\Users\wcinv\AppData\Local\Programs\balena-etcher\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:188
wrapped @ C:\Users\wcinv\AppData\Local\Programs\balena-etcher\resources\app.asar\node_modules\raven-js\dist\raven.js:444
invokeGuardedCallbackDev @ C:\Users\wcinv\AppData\Local\Programs\balena-etcher\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:237
invokeGuardedCallback @ C:\Users\wcinv\AppData\Local\Programs\balena-etcher\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:292
commitRootImpl @ C:\Users\wcinv\AppData\Local\Programs\balena-etcher\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:22541
unstable_runWithPriority @ C:\Users\wcinv\AppData\Local\Programs\balena-etcher\resources\app.asar\node_modules\scheduler\cjs\scheduler.development.js:653
runWithPriority$1 @ C:\Users\wcinv\AppData\Local\Programs\balena-etcher\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:11039
commitRoot @ C:\Users\wcinv\AppData\Local\Programs\balena-etcher\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:22381
finishSyncRender @ C:\Users\wcinv\AppData\Local\Programs\balena-etcher\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:21807
performSyncWorkOnRoot @ C:\Users\wcinv\AppData\Local\Programs\balena-etcher\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:21793
(anonymous) @ C:\Users\wcinv\AppData\Local\Programs\balena-etcher\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:11089
unstable_runWithPriority @ C:\Users\wcinv\AppData\Local\Programs\balena-etcher\resources\app.asar\node_modules\scheduler\cjs\scheduler.development.js:653
runWithPriority$1 @ C:\Users\wcinv\AppData\Local\Programs\balena-etcher\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:11039
flushSyncCallbackQueueImpl @ C:\Users\wcinv\AppData\Local\Programs\balena-etcher\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:11084
flushSyncCallbackQueue @ C:\Users\wcinv\AppData\Local\Programs\balena-etcher\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:11072
scheduleUpdateOnFiber @ C:\Users\wcinv\AppData\Local\Programs\balena-etcher\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:21199
enqueueSetState @ C:\Users\wcinv\AppData\Local\Programs\balena-etcher\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:12639
Component.setState @ C:\Users\wcinv\AppData\Local\Programs\balena-etcher\resources\app.asar\node_modules\react\cjs\react.development.js:471
(anonymous) @ gui.js:3898
changeHandler @ gui.js:785
dispatch @ C:\Users\wcinv\AppData\Local\Programs\balena-etcher\resources\app.asar\node_modules\redux\lib\redux.js:228
setDrives @ gui.js:2182
setDrives @ gui.js:3439
addDrive @ gui.js:3451
async function (async)
addDrive @ gui.js:3446
emit @ events.js:203
onAttach @ C:\Users\wcinv\AppData\Local\Programs\balena-etcher\resources\app.asar\node_modules\etcher-sdk\build\scanner\scanner.js:34
emit @ events.js:203
scan @ C:\Users\wcinv\AppData\Local\Programs\balena-etcher\resources\app.asar\node_modules\etcher-sdk\build\scanner\adapters\block-device.js:94
async function (async)
scan @ C:\Users\wcinv\AppData\Local\Programs\balena-etcher\resources\app.asar\node_modules\etcher-sdk\build\scanner\adapters\block-device.js:77
scanLoop @ C:\Users\wcinv\AppData\Local\Programs\balena-etcher\resources\app.asar\node_modules\etcher-sdk\build\scanner\adapters\block-device.js:68
start @ C:\Users\wcinv\AppData\Local\Programs\balena-etcher\resources\app.asar\node_modules\etcher-sdk\build\scanner\adapters\block-device.js:59
(anonymous) @ C:\Users\wcinv\AppData\Local\Programs\balena-etcher\resources\app.asar\node_modules\etcher-sdk\build\scanner\scanner.js:59
(anonymous) @ C:\Users\wcinv\AppData\Local\Programs\balena-etcher\resources\app.asar\node_modules\etcher-sdk\build\scanner\scanner.js:51
start @ C:\Users\wcinv\AppData\Local\Programs\balena-etcher\resources\app.asar\node_modules\etcher-sdk\build\scanner\scanner.js:50
(anonymous) @ gui.js:3478
__webpack_require__ @ gui.js:21
(anonymous) @ gui.js:85
(anonymous) @ gui.js:88
Show 2 more frames
C:\Users\wcinv\AppData\Local\Programs\balena-etcher\resources\app.asar\node_modules\raven-js\dist\raven.js:58 {"stack":"TypeError: Cannot read property 'path' of undefined\n    at isSourceDrive (file:///C:/Users/wcinv/AppData/Local/Programs/balena-etcher/resources/app.asar/generated/gui.js:1730:19)\n    at Object.getDriveImageCompatibilityStatuses (file:///C:/Users/wcinv/AppData/Local/Programs/balena-etcher/resources/app.asar/generated/gui.js:1822:9)\n    at DriveCompatibilityWarning (file:///C:/Users/wcinv/AppData/Local/Programs/balena-etcher/resources/app.asar/generated/gui.js:5060:55)\n    at renderWithHooks (C:\\Users\\wcinv\\AppData\\Local\\Programs\\balena-etcher\\resources\\app.asar\\node_modules\\react-dom\\cjs\\react-dom.development.js:14803:18)\n    at mountIndeterminateComponent (C:\\Users\\wcinv\\AppData\\Local\\Programs\\balena-etcher\\resources\\app.asar\\node_modules\\react-dom\\cjs\\react-dom.development.js:17482:13)\n    at beginWork (C:\\Users\\wcinv\\AppData\\Local\\Programs\\balena-etcher\\resources\\app.asar\\node_modules\\react-dom\\cjs\\react-dom.development.js:18596:16)\n    at HTMLUnknownElement.callCallback (C:\\Users\\wcinv\\AppData\\Local\\Programs\\balena-etcher\\resources\\app.asar\\node_modules\\react-dom\\cjs\\react-dom.development.js:188:14)\n    at HTMLUnknownElement.wrapped (C:\\Users\\wcinv\\AppData\\Local\\Programs\\balena-etcher\\resources\\app.asar\\node_modules\\raven-js\\dist\\raven.js:444:21)\n    at Object.invokeGuardedCallbackDev (C:\\Users\\wcinv\\AppData\\Local\\Programs\\balena-etcher\\resources\\app.asar\\node_modules\\react-dom\\cjs\\react-dom.development.js:237:16)\n    at invokeGuardedCallback (C:\\Users\\wcinv\\AppData\\Local\\Programs\\balena-etcher\\resources\\app.asar\\node_modules\\react-dom\\cjs\\react-dom.development.js:292:31)\n    at beginWork$1 (C:\\Users\\wcinv\\AppData\\Local\\Programs\\balena-etcher\\resources\\app.asar\\node_modules\\react-dom\\cjs\\react-dom.development.js:23203:7)\n    at performUnitOfWork (C:\\Users\\wcinv\\AppData\\Local\\Programs\\balena-etcher\\resources\\app.asar\\node_modules\\react-dom\\cjs\\react-dom.development.js:22154:12)\n    at workLoopSync (C:\\Users\\wcinv\\AppData\\Local\\Programs\\balena-etcher\\resources\\app.asar\\node_modules\\react-dom\\cjs\\react-dom.development.js:22130:22)\n    at performSyncWorkOnRoot (C:\\Users\\wcinv\\AppData\\Local\\Programs\\balena-etcher\\resources\\app.asar\\node_modules\\react-dom\\cjs\\react-dom.development.js:21756:9)\n    at C:\\Users\\wcinv\\AppData\\Local\\Programs\\balena-etcher\\resources\\app.asar\\node_modules\\react-dom\\cjs\\react-dom.development.js:11089:24\n    at unstable_runWithPriority (C:\\Users\\wcinv\\AppData\\Local\\Programs\\balena-etcher\\resources\\app.asar\\node_modules\\scheduler\\cjs\\scheduler.development.js:653:12)\n    at runWithPriority$1 (C:\\Users\\wcinv\\AppData\\Local\\Programs\\balena-etcher\\resources\\app.asar\\node_modules\\react-dom\\cjs\\react-dom.development.js:11039:10)\n    at flushSyncCallbackQueueImpl (C:\\Users\\wcinv\\AppData\\Local\\Programs\\balena-etcher\\resources\\app.asar\\node_modules\\react-dom\\cjs\\react-dom.development.js:11084:7)\n    at flushSyncCallbackQueue (C:\\Users\\wcinv\\AppData\\Local\\Programs\\balena-etcher\\resources\\app.asar\\node_modules\\react-dom\\cjs\\react-dom.development.js:11072:3)\n    at scheduleUpdateOnFiber (C:\\Users\\wcinv\\AppData\\Local\\Programs\\balena-etcher\\resources\\app.asar\\node_modules\\react-dom\\cjs\\react-dom.development.js:21199:9)\n    at Object.enqueueSetState (C:\\Users\\wcinv\\AppData\\Local\\Programs\\balena-etcher\\resources\\app.asar\\node_modules\\react-dom\\cjs\\react-dom.development.js:12639:5)\n    at MainPage.Component.setState (C:\\Users\\wcinv\\AppData\\Local\\Programs\\balena-etcher\\resources\\app.asar\\node_modules\\react\\cjs\\react.development.js:471:16)\n    at file:///C:/Users/wcinv/AppData/Local/Programs/balena-etcher/resources/app.asar/generated/gui.js:3898:18\n    at changeHandler (file:///C:/Users/wcinv/AppData/Local/Programs/balena-etcher/resources/app.asar/generated/gui.js:785:13)\n    at Object.dispatch (C:\\Users\\wcinv\\AppData\\Local\\Programs\\balena-etcher\\resources\\app.asar\\node_modules\\redux\\lib\\redux.js:228:7)\n    at Object.setDrives (file:///C:/Users/wcinv/AppData/Local/Programs/balena-etcher/resources/app.asar/generated/gui.js:2182:19)\n    at setDrives (file:///C:/Users/wcinv/AppData/Local/Programs/balena-etcher/resources/app.asar/generated/gui.js:3439:21)\n    at Scanner.addDrive (file:///C:/Users/wcinv/AppData/Local/Programs/balena-etcher/resources/app.asar/generated/gui.js:3451:5)","message":"Cannot read property 'path' of undefined"}
```

**Comment by thundron** [comment]
This should be solved with PR #3165
