### ISSUE TITLE
MacOS v1.5.103 - settings cannot be changed

### ISSUE THREAD

**Issue by sbytnar** [balena-io/etcher#3279]
- **Etcher version:** 1.5.103
- **Operating system and architecture:** MacOS Catalina 10.15.6 (19G2006)
- **Image flashed:** None.
- **Do you see any meaningful error information in the DevTools?** Yes

gui.js:48791 {"stack":"ReferenceError: exports is not defined\n    at set (file:///Applications/balenaEtcher-1.5.103.app/Contents/Resources/app/generated/gui.js:63074:13)\n    at async toggleSetting (file:///Applications/balenaEtcher-1.5.103.app/Contents/Resources/app/generated/gui.js:74436:13)","message":"exports is not defined"}
console.<computed> @ gui.js:48791
logException @ gui.js:56159
(anonymous) @ gui.js:80196

- **Isolation:** This problem does not occur with v1.5.102.

**Comment by thundron** [comment]
Thanks for the report, we'll make a quick PR to fix the issue
