### ISSUE TITLE
Cannot burn Pop!_OS  20.04 LTS to a Patriot Rage XT 64GB

### ISSUE THREAD

**Issue by PhantomR** [balena-io/etcher#3319]
- **Etcher version : 1.5.109** 
- **Operating system and architecture: ** Windows 10 2004 (19041.508) x64, also tested on latest Insider (in there the installation also fails, but before that an 'Autoplay' notification keeps popping and disappearing in the lower-right corner)** 
- **Image flashed: pop-os_20.04_amd64_nvidia_13.iso 
- **Do you see any meaningful error information in the DevTools?** I am pasting the entire log for you to judge :)

```
gui.js:48927 Sat Oct 10 2020 23:11:40 GMT+0300 (Eastern European Summer Time) Open image selector ({"sample":0.1,"applicationSessionUuid":"7b50062f-e302-43ff-8645-b1316d9dec95","flashingWorkflowUuid":"a50c3255-b733-47ee-902f-7486b538c296"})
gui.js:48927 Sat Oct 10 2020 23:11:42 GMT+0300 (Eastern European Summer Time) Select image ({"image":{"size":2566914048,"name":"pop-os_20.04_amd64_nvidia_13.iso","hasMBR":true,"partitions":[{"offset":165888,"size":4194304,"type":239,"index":1}],"extension":"iso","path":"E:\\Users\\Alexandru Dan Duna\\Downloads\\pop-os_20.04_amd64_nvidia_13.iso","logo":false,"blockMap":false},"sample":0.1,"applicationSessionUuid":"7b50062f-e302-43ff-8645-b1316d9dec95","flashingWorkflowUuid":"a50c3255-b733-47ee-902f-7486b538c296"})
gui.js:48927 Sat Oct 10 2020 23:11:44 GMT+0300 (Eastern European Summer Time) Toggle drive ({"drive":{"size":61958258688,"isVirtual":false,"enumerator":"USBSTOR","logicalBlockSize":512,"raw":"\\\\.\\PhysicalDrive3","error":null,"isReadOnly":false,"displayName":"\\\\.\\PhysicalDrive3","blockSize":512,"isSCSI":false,"isRemovable":true,"device":"\\\\.\\PhysicalDrive3","busVersion":"2.0","isSystem":false,"busType":"USB","isCard":false,"isUSB":true,"devicePath":null,"mountpoints":[],"description":"Patriot Memory USB Device","isUAS":false},"previouslySelected":false,"sample":0.1,"applicationSessionUuid":"7b50062f-e302-43ff-8645-b1316d9dec95","flashingWorkflowUuid":"a50c3255-b733-47ee-902f-7486b538c296"})
gui.js:48927 Sat Oct 10 2020 23:11:50 GMT+0300 (Eastern European Summer Time) Flash ({"image":{"size":2566914048,"name":"pop-os_20.04_amd64_nvidia_13.iso","hasMBR":true,"partitions":[{"offset":165888,"size":4194304,"type":239,"index":1}],"extension":"iso","path":"E:\\Users\\Alexandru Dan Duna\\Downloads\\pop-os_20.04_amd64_nvidia_13.iso"},"drives":[{"size":61958258688,"isVirtual":false,"enumerator":"USBSTOR","logicalBlockSize":512,"raw":"\\\\.\\PhysicalDrive3","error":null,"isReadOnly":false,"displayName":"\\\\.\\PhysicalDrive3","blockSize":512,"isSCSI":false,"isRemovable":true,"device":"\\\\.\\PhysicalDrive3","busVersion":"2.0","isSystem":false,"busType":"USB","isCard":false,"isUSB":true,"devicePath":null,"mountpoints":[],"description":"Patriot Memory USB Device","isUAS":false}],"driveCount":1,"uuid":"56508a19-cf5e-43f2-98c9-10101fb36c70","status":"started","flashInstanceUuid":"56508a19-cf5e-43f2-98c9-10101fb36c70","unmountOnSuccess":true,"validateWriteOnSuccess":true,"sample":0.1,"applicationSessionUuid":"7b50062f-e302-43ff-8645-b1316d9dec95","flashingWorkflowUuid":"a50c3255-b733-47ee-902f-7486b538c296"})
gui.js:48927 Elevating command: C:\Users\dunaa\AppData\Local\Programs\balena-etcher\balenaEtcher.exe C:\Users\dunaa\AppData\Local\Programs\balena-etcher\resources\app\generated\child-writer.js
gui.js:48927 Sat Oct 10 2020 23:11:50 GMT+0300 (Eastern European Summer Time) SafeWebview loaded ({"event":{"id":39,"url":"https://assets.balena.io/etcher-featured/index.html?borderRight=false&darkBackground=true&etcher-version=1.5.109&api-version=2&optOutAnalytics=false","method":"GET","timestamp":1602360710866.3708,"resourceType":"mainFrame","ip":"2606:4700:3032::681f:539d","fromCache":false,"statusLine":"HTTP/1.1 200","statusCode":200,"responseHeaders":{"access-control-allow-origin":["*"],"age":["585"],"cache-control":["max-age=600"],"cf-cache-status":["DYNAMIC"],"cf-ray":["5e0405d5387a0726-LHR"],"cf-request-id":["05b661f94400000726b29c3200000001"],"content-encoding":["br"],"content-type":["text/html; charset=utf-8"],"date":["Sat, 10 Oct 2020 23:11:50 GMT"],"expect-ct":["max-age=604800, report-uri=\"https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct\""],"expires":["Wed, 30 Sep 2020 04:36:32 GMT"],"last-modified":["Tue, 18 Aug 2020 09:51:57 GMT"],"nel":["{\"report_to\":\"cf-nel\",\"max_age\":604800}"],"report-to":["{\"endpoints\":[{\"url\":\"https:\\/\\/a.nel.cloudflare.com\\/report?lkg-colo=21&lkg-time=1602371511\"}],\"group\":\"cf-nel\",\"max_age\":604800}"],"server":["cloudflare"],"status":["200"],"vary":["Accept-Encoding"],"via":["1.1 varnish"],"x-cache":["HIT"],"x-cache-hits":["2"],"x-fastly-request-id":["d473eee97d5d35ff12f1b76a60bfdcb67294072b"],"x-github-request-id":["58BE:D895:89DF7B1:930CF26:5F740AEC"],"x-origin-cache":["HIT"],"x-proxy-cache":["HIT"],"x-served-by":["cache-lcy19225-LCY"],"x-timer":["S1602371511.603478,VS0,VE0"]},"referrer":"","error":"net::OK"},"sample":0.1,"applicationSessionUuid":"7b50062f-e302-43ff-8645-b1316d9dec95","flashingWorkflowUuid":"a50c3255-b733-47ee-902f-7486b538c296"})
gui.js:6038  0 devices, 0% at 0.00 MB/s (total 0.00 MB/s)  with 0 failed devices
gui.js:48927 Successfully connected to IPC server: etcher-server-9004, socket root C:\Users\dunaa\AppData\Local\Temp\
gui.js:48927 Image: E:\Users\Alexandru Dan Duna\Downloads\pop-os_20.04_amd64_nvidia_13.iso
gui.js:48927 Devices: \\.\PhysicalDrive3
gui.js:48927 Umount on success: true
gui.js:48927 Validate on success: true
gui.js:48927 Auto blockmapping: true
gui.js:48927 Decompress first: true
gui.js:48927 Sat Oct 10 2020 23:12:12 GMT+0300 (Eastern European Summer Time) Flash error ({"image":{"size":2566914048,"name":"pop-os_20.04_amd64_nvidia_13.iso","hasMBR":true,"partitions":[{"offset":165888,"size":4194304,"type":239,"index":1}],"extension":"iso","path":"E:\\Users\\Alexandru Dan Duna\\Downloads\\pop-os_20.04_amd64_nvidia_13.iso"},"drives":[{"size":61958258688,"isVirtual":false,"enumerator":"USBSTOR","logicalBlockSize":512,"raw":"\\\\.\\PhysicalDrive3","error":null,"isReadOnly":false,"displayName":"\\\\.\\PhysicalDrive3","blockSize":512,"isSCSI":false,"isRemovable":true,"device":"\\\\.\\PhysicalDrive3","busVersion":"2.0","isSystem":false,"busType":"USB","isCard":false,"isUSB":true,"devicePath":null,"mountpoints":[],"description":"Patriot Memory USB Device","isUAS":false}],"driveCount":1,"uuid":"56508a19-cf5e-43f2-98c9-10101fb36c70","flashInstanceUuid":"56508a19-cf5e-43f2-98c9-10101fb36c70","unmountOnSuccess":true,"validateWriteOnSuccess":true,"error":{"name":"Error","message":"Couldn't clean the drive, Command failed: diskpart s n (code 2147942405)","stack":"Error: Couldn't clean the drive, Command failed: diskpart s n (code 2147942405)\n    at Object.exports.clean (C:\\Users\\dunaa\\AppData\\Local\\Programs\\balena-etcher\\resources\\app\\generated\\child-writer.js:17513:27)\n    at async BlockDevice._open (C:\\Users\\dunaa\\AppData\\Local\\Programs\\balena-etcher\\resources\\app\\generated\\child-writer.js:2782:13)\n    at async BlockDevice.open (C:\\Users\\dunaa\\AppData\\Local\\Programs\\balena-etcher\\resources\\app\\generated\\child-writer.js:492:17)\n    at async n    at async Promise.all (index 0)\n    at async MultiDestination._open (C:\\Users\\dunaa\\AppData\\Local\\Programs\\balena-etcher\\resources\\app\\generated\\child-writer.js:6015:13)\n    at async MultiDestination.open (C:\\Users\\dunaa\\AppData\\Local\\Programs\\balena-etcher\\resources\\app\\generated\\child-writer.js:492:17)\n    at async Promise.all (index 1)\n    at async pipeSourceToDestinations (C:\\Users\\dunaa\\AppData\\Local\\Programs\\balena-etcher\\resources\\app\\generated\\child-writer.js:10979:9)\n    at async Object.decompressThenFlash (C:\\Users\\dunaa\\AppData\\Local\\Programs\\balena-etcher\\resources\\app\\generated\\child-writer.js:10915:20)"},"sample":0.1,"applicationSessionUuid":"7b50062f-e302-43ff-8645-b1316d9dec95","flashingWorkflowUuid":"a50c3255-b733-47ee-902f-7486b538c296"})
gui.js:48927 Finish: 0
gui.js:48927 Terminating IPC server
gui.js:48927 Flash results {results: {…}, cancelled: false}cancelled: falseresults: {bytesWritten: 0, devices: {…}, errors: Array(1), sourceMetadata: {…}}__proto__: Object
gui.js:48927 Sat Oct 10 2020 23:12:13 GMT+0300 (Eastern European Summer Time) Write failed ({"image":{"size":2566914048,"name":"pop-os_20.04_amd64_nvidia_13.iso","hasMBR":true,"partitions":[{"offset":165888,"size":4194304,"type":239,"index":1}],"extension":"iso","path":"E:\\Users\\Alexandru Dan Duna\\Downloads\\pop-os_20.04_amd64_nvidia_13.iso"},"drives":[{"size":61958258688,"isVirtual":false,"enumerator":"USBSTOR","logicalBlockSize":512,"raw":"\\\\.\\PhysicalDrive3","error":null,"isReadOnly":false,"displayName":"\\\\.\\PhysicalDrive3","blockSize":512,"isSCSI":false,"isRemovable":true,"device":"\\\\.\\PhysicalDrive3","busVersion":"2.0","isSystem":false,"busType":"USB","isCard":false,"isUSB":true,"devicePath":null,"mountpoints":[],"description":"Patriot Memory USB Device","isUAS":false}],"driveCount":1,"uuid":"56508a19-cf5e-43f2-98c9-10101fb36c70","status":"failed","flashInstanceUuid":"56508a19-cf5e-43f2-98c9-10101fb36c70","unmountOnSuccess":true,"validateWriteOnSuccess":true,"error":{"description":"Please try again, and contact the Etcher team if the problem persists","report":false},"sample":0.1,"applicationSessionUuid":"7b50062f-e302-43ff-8645-b1316d9dec95","flashingWorkflowUuid":"a50c3255-b733-47ee-902f-7486b538c296"})
gui.js:48927 {"stack":"Error: The writer process ended unexpectedly\n    at createError (file:///C%3A/Users/dunaa/AppData/Local/Programs/balena-etcher/resources/app/generated/gui.js:63138:23)\n    at createUserError (file:///C%3A/Users/dunaa/AppData/Local/Programs/balena-etcher/resources/app/generated/gui.js:63149:16)\n    at Server.<anonymous> (file:///C%3A/Users/dunaa/AppData/Local/Programs/balena-etcher/resources/app/generated/gui.js:79356:28)","message":"The writer process ended unexpectedly","description":"Please try again, and contact the Etcher team if the problem persists","report":false,"image":"pop-os_20.04_amd64_nvidia_13.iso"}
console.<computed> @ gui.js:48927
logException @ gui.js:56295
flashImageToDrive @ gui.js:79583
async function (async)
flashImageToDrive @ gui.js:79572
tryFlash @ gui.js:79662
callback @ gui.js:79684
ba @ gui.js:42470
ja @ gui.js:42484
ka @ gui.js:42487
oa @ gui.js:42501
lc @ gui.js:43172
jc @ gui.js:43166
mc @ gui.js:43183
sc @ gui.js:43252
Ia @ gui.js:48482
Ma @ gui.js:42580
Rc @ gui.js:43518
id @ gui.js:43487
exports.unstable_runWithPriority @ gui.js:48811
cg @ gui.js:44679
Ga @ gui.js:48470
gd @ gui.js:43477
```

**Comment by shawaj** [comment]
@PhantomR could you try updating to the latest version [v1.5.112](HTTPS://etcher.io) and see if that fixes the issue?
