### ISSUE TITLE
Verification always fails (Error: EIO: i/o error, read) (Linux, Fedora)

### ISSUE THREAD

**Issue by T-vK** [balena-io/etcher#3625]
- **Etcher version:** 1.5.122-x64 (AppImage) and 1.6.0-1.x86_64 (RPM)
- **Operating system and architecture:** Linux (Fedora 33) x64
- **Image flashed:** RaspbianOS, Ubuntu, Fedora, SamplerBox and many more. It happens no matter which image I use.

I tried different SD cards and different card readers and it made no difference. I also tried using different USB ports (USB 2.0, USB 3.0, USB C, ...) and I also tried it another computer that runs Fedora 32 x64 (KDE spin) as well. Same result every time, no matter if I use 1.5.122 or 1.6.0-1 and no matter if I sue the AppImage or the RPM version.

- **Do you see any meaningful error information in the DevTools?** 
Yes, after flashing, during the verification I get this:
```
Verifying 1 device, 4% at 28.30 MB/s (total 28.30 MB/s) eta in 34s with 0 failed devices
gui.js:51110 Tue Nov 02 2021 10:49:53 GMT+0100 (Central European Standard Time) Input/output error ({"image":{"size":1363148800,"name":"samplerbox_20170710.img","hasMBR":true,"partitions":[{"offset":1048576,"size":67108864,"type":12,"index":1},{"offset":68157440,"size":1294991360,"type":131,"index":2}],"extension":"img","path":"/home/fedora/Downloads/samplerbox_20170710.img"},"drives":[{"size":32010928128,"isVirtual":false,"enumerator":"lsblk:json","logicalBlockSize":512,"raw":"/dev/sdd","error":null,"isReadOnly":false,"displayName":"/dev/sdd","blockSize":512,"isSCSI":false,"isRemovable":true,"device":"/dev/sdd","busVersion":null,"isSystem":false,"busType":"USB","isCard":null,"isUSB":true,"devicePath":"/dev/disk/by-path/pci-0000:27:00.3-usb-0:1:1.0-scsi-0:0:0:0","mountpoints":[],"description":"Generic STORAGE_DEVICE (BOOT, ROOT)","isUAS":null,"partitionTableType":"mbr"}],"driveCount":1,"uuid":"f720b6bc-113e-4202-ba7f-29e63d678117","flashInstanceUuid":"f720b6bc-113e-4202-ba7f-29e63d678117","sample":0.1,"applicationSessionUuid":"da56c83c-b55a-4dcc-93c6-f1292938a914","flashingWorkflowUuid":"fa98f7ca-f891-4dd9-bc5b-4344323f6dff"})
gui.js:38454 Verifying 1 device, 6% at 28.80 MB/s (total 28.80 MB/s) eta in 33s with 0 failed devices
Finish: 71303168
gui.js:51110 Terminating IPC server
Flash results 
{
    "results": {
        "bytesWritten": 71303168,
        "devices": {
            "failed": 1,
            "successful": 0
        },
        "errors": [
            {
                "name": "Error",
                "description": "Generic STORAGE_DEVICE (BOOT, ROOT)",
                "code": "EIO",
                "syscall": "read",
                "errno": -5,
                "device": "/dev/sdd"
            }
        ],
        "sourceMetadata": {
            "size": 1363148800,
            "name": "samplerbox_20170710.img",
            "blocks": [
                ...
            ],
            "blockmappedSize": 1024458752
        },
        "averageFlashingSpeed": 15689696.7914848
    },
    "cancelled": false,
    "skip": false
}
```

I also get some certificate errors:
```
gui.js:51110 {"message":"certificate has expired","stack":"Error: certificate has expired\n    at TLSSocket.onConnectSecure (_tls_wrap.js:1497:34)\n    at TLSSocket.emit (events.js:315:20)\n    at TLSSocket._finishInit (_tls_wrap.js:932:8)\n    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:706:12)","config":{"url":"https://balena.io/etcher/static/config.json","method":"get","headers":{"Accept":"application/json, text/plain, */*","User-Agent":"axios/1.5.122"},"transformRequest":[null],"transformResponse":[null],"timeout":0,"responseType":"json","xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1},"code":"CERT_HAS_EXPIRED"}
console.<computed> @ gui.js:51110
```

And I also get:
```
Message from SafeWebview: Error: Not supported
```

**Comment by T-vK** [comment]
After trying it on Windows, which failed as well, I went through 8 different card readers and then finally found one that yielded successful results. So apparently I own 7 card readers that used to work fine for years and then all stopped working at the same time for no apparent reason. I literally flashed hundreds of images with those in the past and now suddenly they don't work anyone. I have no idea why. Anyway, I'm gonna close the issue now.
