### ISSUE TITLE
Ubuntu flash failed with no error

### ISSUE THREAD

**Issue by llamafilm** [balena-io/etcher#3651]
- **Etcher version:** 1.7.1
- **Operating system and architecture:** macOS 11.6 Intel
- **Image flashed:** ubuntu-20.04.3-live-server-amd64.iso
- **Do you see any meaningful error information in the DevTools?** 

I tried multiple times to flash this ISO but it fails after just a few seconds with no error message.  I verified the sha256 checksum against Ubuntu website (f8e3086f3cea0fb3fefb29937ab5ed9d19e767079633960ccb50e76153effc98).  The USB stick was freshly erased as FAT32 using Disk Utility.  I tried both GUID and MBR.  It's a 64GB USB-C Sandisk drive.

```
index.css:1 Failed to load resource: net::ERR_FILE_NOT_FOUND
electron/js2c/renderer_init.js:13 (electron) The remote module is deprecated. Use https://github.com/electron/remote instead.
log @ electron/js2c/renderer_init.js:13
gui.js:364  _____ _       _
|  ___| |     | |
| |__ | |_ ___| |__   ___ _ __
|  __|| __/ __| '_ \ / _ \ '__|
| |___| || (__| | | |  __/ |
\____/ \__\___|_| |_|\___|_|

Interested in joining the Etcher team?
Drop us a line at join+etcher@balena.io

Version = 1.7.1, Type = dmg
gui.js:46 Thu Dec 09 2021 10:26:23 GMT-0800 (Pacific Standard Time) Application start ({"packageType":"dmg","version":"1.7.1","sample":0.1,"applicationSessionUuid":"638fbd0e-900a-4f9a-9774-e6a0a0626ce8","flashingWorkflowUuid":"e9927a96-c209-4f9d-abc0-e61cf4cb5b15"})
gui.js:46 [Axios v1.7.1] Transitional option 'clarifyTimeoutError' has been deprecated since v1.0.0 and will be removed in the near future
console.<computed> @ gui.js:46
gui.js:46 [Axios v1.7.1] Transitional option 'forcedJSONParsing' has been deprecated since v1.0.0 and will be removed in the near future
console.<computed> @ gui.js:46
gui.js:46 [Axios v1.7.1] Transitional option 'silentJSONParsing' has been deprecated since v1.0.0 and will be removed in the near future
console.<computed> @ gui.js:46
gui.js:46 {"message":"certificate has expired","stack":"Error: certificate has expired\n    at TLSSocket.onConnectSecure (_tls_wrap.js:1497:34)\n    at TLSSocket.emit (events.js:315:20)\n    at TLSSocket._finishInit (_tls_wrap.js:932:8)\n    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:706:12)","config":{"url":"https://balena.io/etcher/static/config.json","method":"get","headers":{"Accept":"application/json, text/plain, */*","User-Agent":"axios/1.7.1"},"transformRequest":[null],"transformResponse":[null],"timeout":0,"responseType":"json","xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1,"transitional":{"silentJSONParsing":true,"forcedJSONParsing":true,"clarifyTimeoutError":false}},"code":"CERT_HAS_EXPIRED"}
console.<computed> @ gui.js:46
gui.js:46 Thu Dec 09 2021 10:26:24 GMT-0800 (Pacific Standard Time) Open image selector ({"sample":0.1,"applicationSessionUuid":"638fbd0e-900a-4f9a-9774-e6a0a0626ce8","flashingWorkflowUuid":"e9927a96-c209-4f9d-abc0-e61cf4cb5b15"})
gui.js:46 Thu Dec 09 2021 10:26:28 GMT-0800 (Pacific Standard Time) Select image ({"image":{"size":1261371392,"name":"ubuntu-20.04.3-live-server-amd64.iso","hasMBR":true,"partitions":[{"offset":335955968,"size":4096000,"type":239,"index":1}],"extension":"iso","path":"/Users/ebalsley/Downloads/ubuntu-20.04.3-live-server-amd64.iso","logo":false,"blockMap":false},"sample":0.1,"applicationSessionUuid":"638fbd0e-900a-4f9a-9774-e6a0a0626ce8","flashingWorkflowUuid":"e9927a96-c209-4f9d-abc0-e61cf4cb5b15"})
gui.js:46 Thu Dec 09 2021 10:26:31 GMT-0800 (Pacific Standard Time) Flash ({"image":{"size":1261371392,"name":"ubuntu-20.04.3-live-server-amd64.iso","hasMBR":true,"partitions":[{"offset":335955968,"size":4096000,"type":239,"index":1}],"extension":"iso","path":"/Users/ebalsley/Downloads/ubuntu-20.04.3-live-server-amd64.iso"},"drives":[{"size":61505273856,"isVirtual":false,"enumerator":"DiskArbitration","logicalBlockSize":512,"raw":"/dev/rdisk3","error":null,"isReadOnly":false,"displayName":"/dev/disk3","blockSize":512,"isSCSI":false,"isRemovable":true,"device":"/dev/disk3","busVersion":null,"isSystem":false,"busType":"USB","isCard":false,"isUSB":true,"devicePath":"IODeviceTree:/PCI0@0/PEG1@1,1/UPSB@0/DSB2@2/XHC2@0","mountpoints":[{"path":"/Volumes/UBUNTU","label":"UBUNTU"}],"description":"USB SanDisk 3.2Gen1 Media","isUAS":null,"partitionTableType":"mbr"}],"driveCount":1,"uuid":"5b07764a-d208-4ea7-8a73-da852b30058a","status":"started","flashInstanceUuid":"5b07764a-d208-4ea7-8a73-da852b30058a","sample":0.1,"applicationSessionUuid":"638fbd0e-900a-4f9a-9774-e6a0a0626ce8","flashingWorkflowUuid":"e9927a96-c209-4f9d-abc0-e61cf4cb5b15"})
gui.js:46 Elevating command: /Applications/balenaEtcher.app/Contents/Frameworks/balenaEtcher Helper (Renderer).app/Contents/MacOS/balenaEtcher Helper (Renderer) /Applications/balenaEtcher.app/Contents/Resources/app/generated/child-writer.js
gui.js:35  0 devices, 0% at 0.00 MB/s (total 0.00 MB/s)  with 0 failed devices
gui.js:46 Thu Dec 09 2021 10:26:33 GMT-0800 (Pacific Standard Time) SafeWebview loaded ({"event":{"id":1,"url":"https://assets.balena.io/etcher-featured/index.html?borderRight=false&darkBackground=true&etcher-version=1.7.1&api-version=2&optOutAnalytics=false","method":"GET","timestamp":1639074391649.7651,"resourceType":"mainFrame","ip":"2606:4700:3034::6815:1d95","fromCache":false,"statusLine":"HTTP/1.1 200","statusCode":200,"responseHeaders":{"access-control-allow-origin":["*"],"age":["254"],"alt-svc":["h3=\":443\"; ma=86400, h3-29=\":443\"; ma=86400, h3-28=\":443\"; ma=86400, h3-27=\":443\"; ma=86400"],"cache-control":["max-age=600"],"cf-cache-status":["DYNAMIC"],"cf-ray":["6bb048441f5f7107-SJC"],"content-encoding":["br"],"content-type":["text/html; charset=utf-8"],"date":["Thu, 09 Dec 2021 18:26:31 GMT"],"expect-ct":["max-age=604800, report-uri=\"https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct\""],"expires":["Thu, 09 Dec 2021 18:27:08 GMT"],"last-modified":["Wed, 08 Dec 2021 20:59:54 GMT"],"nel":["{\"success_fraction\":0,\"report_to\":\"cf-nel\",\"max_age\":604800}"],"report-to":["{\"endpoints\":[{\"url\":\"https:\\/\\/a.nel.cloudflare.com\\/report\\/v3?s=33lrQbteC62D%2B2ygktbdlatYJwOwUYuNk8J62q3a5PpHLV5PsPcfr5fFWqJCstOLWsx5lXv3UJGLul3CXwqXDpuHpN%2BRwhK3JtMoCgwtocYfW24pRLe9ekBA3yCIpbDk6C1r43pDAB7PfoFX4CZz\"}],\"group\":\"cf-nel\",\"max_age\":604800}"],"server":["cloudflare"],"vary":["Accept-Encoding"],"via":["1.1 varnish"],"x-cache":["HIT"],"x-cache-hits":["1"],"x-fastly-request-id":["81af480fc3a640b24ef15b75dae7c62bbd6a3bae"],"x-github-request-id":["0A02:5C2F:2E25EB:364292:61B24824"],"x-proxy-cache":["MISS"],"x-served-by":["cache-sjc10027-SJC"],"x-timer":["S1639074392.716710,VS0,VE1"]},"referrer":"","error":"net::OK"},"sample":0.1,"applicationSessionUuid":"638fbd0e-900a-4f9a-9774-e6a0a0626ce8","flashingWorkflowUuid":"e9927a96-c209-4f9d-abc0-e61cf4cb5b15"})
gui.js:46 Terminating IPC server
gui.js:46 Flash results Object
gui.js:46 Thu Dec 09 2021 10:26:33 GMT-0800 (Pacific Standard Time) Elevation cancelled ({"image":{"size":1261371392,"name":"ubuntu-20.04.3-live-server-amd64.iso","hasMBR":true,"partitions":[{"offset":335955968,"size":4096000,"type":239,"index":1}],"extension":"iso","path":"/Users/ebalsley/Downloads/ubuntu-20.04.3-live-server-amd64.iso"},"drives":[{"size":61505273856,"isVirtual":false,"enumerator":"DiskArbitration","logicalBlockSize":512,"raw":"/dev/rdisk3","error":null,"isReadOnly":false,"displayName":"/dev/disk3","blockSize":512,"isSCSI":false,"isRemovable":true,"device":"/dev/disk3","busVersion":null,"isSystem":false,"busType":"USB","isCard":false,"isUSB":true,"devicePath":"IODeviceTree:/PCI0@0/PEG1@1,1/UPSB@0/DSB2@2/XHC2@0","mountpoints":[{"path":"/Volumes/UBUNTU","label":"UBUNTU"}],"description":"USB SanDisk 3.2Gen1 Media","isUAS":null,"partitionTableType":"mbr"}],"driveCount":1,"uuid":"5b07764a-d208-4ea7-8a73-da852b30058a","status":"cancel","flashInstanceUuid":"5b07764a-d208-4ea7-8a73-da852b30058a","sample":0.1,"applicationSessionUuid":"638fbd0e-900a-4f9a-9774-e6a0a0626ce8","flashingWorkflowUuid":"e9927a96-c209-4f9d-abc0-e61cf4cb5b15"})
```

**Comment by lurch** [comment]
Similar to #3459 ?

**Comment by llamafilm** [comment]
Yes thank you!  Running as sudo works.
