### ISSUE TITLE
Cannot flash image on opensuse tumbleweed

### ISSUE THREAD

**Issue by Garbg** [balena-io/etcher#3972]
- **Etcher version:** 
1.13.1 appimage
- **Operating system and architecture:** 
Operating System: openSUSE Tumbleweed 20230103
KDE Plasma Version: 5.26.4
KDE Frameworks Version: 5.101.0
Qt Version: 5.15.7
Kernel Version: 6.1.2-1-default (64-bit)
Graphics Platform: X11
Processors: 20 × Intel® Core™ i9-10850K CPU @ 3.60GHz
Memory: 31.3 GiB of RAM
Graphics Processor: AMD Radeon RX 6600
Manufacturer: Micro-Star International Co., Ltd.
Product Name: MS-7C79
System Version: 1.0
- **Image flashed:** 
Bliss OS 11.13 GMS Stable (x86_64)
- **What do you think should have happened:** 
It should have flashed the image correctly
- **What happened:**
After entering my password it said:

Attention
Something went wrong. If it is a compressed image, please check if the archive is not corrupted.
The elevated process died unexpectedly

- **Do you see any meaningful error information in the DevTools?** 
  * {"stack":"Error: The elevated process died unexpectedly\n    at createError (file:///tmp/.mount_balena4mcBhk/resources/app/generated/gui.js:37:219752)\n    at Object.createUserError (file:///tmp/.mount_balena4mcBhk/resources/app/generated/gui.js:37:219965)\n    at file:///tmp/.mount_balena4mcBhk/resources/app/generated/gui.js:341:5102\n    at async withTmpFile (file:///tmp/.mount_balena4mcBhk/resources/app/generated/gui.js:1:408539)\n    at async elevateCommand (file:///tmp/.mount_balena4mcBhk/resources/app/generated/gui.js:341:4333)\n    at async Server.<anonymous> (file:///tmp/.mount_balena4mcBhk/resources/app/generated/gui.js:341:8437)","message":"The elevated process died unexpectedly","description":"The process error code was 255","report":false,"image":"Bliss-v11.13--OFFICIAL-20201113-1525_x86_64_k-k4.19.122-ax86-ga-rmi_m-20.1.0-llvm90_dgc-t3_gms_intelhd.iso"}
console.<computed> @ gui.js:37
  * {"stack":"Error: Error invoking remote method 'enable-screensaver': No handler registered for 'enable-screensaver'\n    at EventEmitter.i.invoke (electron/js2c/renderer_init.js:73:529)","message":"Error invoking remote method 'enable-screensaver': No handler registered for 'enable-screensaver'"}

**Comment by Garbg** [comment]
I checked, it's not corrupted
