### ISSUE TITLE
Flashing xz compressed file from URL fails

### ISSUE THREAD

**Issue by agners** [balena-io/etcher#4064]
- **Etcher version:** 1.18.4-x64
- **Operating system and architecture:** Arch Linux x86-64
- **Image flashed:** https://github.com/home-assistant/operating-system/releases/download/10.1/haos_odroid-n2-10.1.img.xz
- **What do you think should have happened:** Flash that image
- **What happened:** Error: The elevated process died unexpectedly
- **Do you see any meaningful error information in the DevTools?** 

```
gui.js:37 Error: The elevated process died unexpectedly
    at createError (gui.js:37:219904)
    at Object.createUserError (gui.js:37:220117)
    at gui.js:341:5180
    at async withTmpFile (gui.js:1:718820)
    at async elevateCommand (gui.js:341:4411)
    at async Server.<anonymous> (gui.js:341:8515)
```

![Screenshot from 2023-05-11 15-09-46](https://github.com/balena-io/etcher/assets/34061/3e5b1077-3905-494d-bb89-6fe6486b1de6)

**Comment by agners** [comment]
Same with the latest preview v1.18.8. An older version I had at hand seems to work (1.5.120).

**Comment by sweavo** [comment]
samesame. thanks for the tip about 1.1.0.x

**Comment by sweavo** [comment]
and 1.10x stalled out at 99% with 20seconds remaining.

**Comment by dfunckt** [comment]
Does it work if you download the file first and try to flash that?

**Comment by c0ffeeca7** [comment]
works for me:

**Etcher version**: 1.18.4-x64
**Operating system and architecture**: Ubuntu x86-64
**Image flashed**: https://github.com/home-assistant/operating-system/releases/download/10.1/haos_odroid-n2-10.1.img.xz, downloaded locally, not flashed from URL

**Comment by agners** [comment]
@dfunckt yes it works when downloading and then installing. We currently document this as work around.

We've discovered that the same is true for MacOS.

Any chance that this gets addressed? It would be really helpful if we could use flashing directly from an URL again.

**Comment by cmccall-epilog** [comment]
I'm also unable to flash from URL, but I don't get an error at all. The progress on bytes written increases until it just about completes and then it stops indefinitely. I can download the image and flash fine, but the workflow problem I'm trying to solve centers around eliminating the download step.

I'm on macOS 14.0

**Comment by lukechilds** [comment]
I get the same issue when flashing `.img.gz` and `.img.xz` from a URL but flashing `.img.zip` works from a URL.

Flashing all three of the above compressed images works when flashing from the locally downloaded file.

**Comment by lukechilds** [comment]
@dfunckt let me know if there's any more information I can provide to help you guys. We reccomend balenaEtcher to all of our users when installing @getumbrel and currently it's slowing down our build process quite a lot because we can't make use of parallel gzip compression on our images and instead use single threaded zip compression to avoid hitting this bug.

**Comment by ShaharHD** [comment]
I have the same issue with `xz` files (not URL)
Happens on `1.19.21` and `1.19.19`
No issue when using the uncompressed version

I don't know at version it stopped working exacly, but used to work before.
I'm on macOS Sonoma 14.5 running on M1 Max

**Comment by lanzer-gaia** [comment]
For anyone who came across this issue.  On MacOS the default unarchiver can decompress an .xz image, while on Windows you can use 7zip archiver.  As mentioned above, writing an uncompressed image will not show any issue.  That's one way to work around this error until a fix arrives.

**Comment by lonely-soul1234** [comment]
used balena etcher linux x64 on ubuntu 24.04.2 LTS to flash a 128GB class 10 TF card from sandisk , the image flashed is ubuntu 24.04 orange pi from joshua-riek. the img.xz failed to be verified multiple times, but I unxz it using defualt tool and flashed properly.
Samething error happened writing the image to TF card (128gb or 32gb) on a Win 10 with balena etcher 1.19.25, either with or without admin privilige.  .xz file failed to flash, but extracted .img works fine.

I guess something is wrong with processing of .xz format. Next time I experience this issue, I will uncompress the .xz file and flash with .img file.
