### ISSUE TITLE
User dont grant permission

### ISSUE THREAD

**Issue by AnimeHeaven** [balena-io/etcher#4072]
- **Etcher version: 1.18.4** 
- **Operating system and architecture:
- Edition	Windows 10 Pro
Version	22H2
Systembuild	19045.2965
Windows Feature Experience Pack 1000.19041.1000.0
Prozessor	AMD Ryzen 7 1700X Eight-Core Processor            3.77 GHz
Installierter RAM	32,0 GB ** 
- **Image flashed: batocera-x86_64-36-20230306.img from https://updates.batocera.org/x86_64/stable/last/batocera-x86_64-36-20230306.img.gz** 

- **What happened: I wanted to flash a USB micro card with 128 GB an it comes the Error "User dont grant permission. I have tried run as admin and a reinstall of the etcher.**
- **Do you see any meaningful error information in the DevTools?** 
gui.js:37 Error: User did not grant permission.
    at gui.js:37:773107
    at ChildProcess.exithandler (node:child_process:415:5)
    at ChildProcess.emit (node:events:526:28)
    at maybeClose (node:internal/child_process:1092:16)
    at ChildProcess._handle.onexit (node:internal/child_process:302:5)

gui.js:37 Error: Error invoking remote method 'enable-screensaver': No handler registered for 'enable-screensaver'
    at o.invoke (node:electron/js2c/renderer_init:57:526)

Elevating command: C:\Users\Stefan\AppData\Local\Programs\balena-etcher\balenaEtcher.exe C:\Users\Stefan\AppData\Local\Programs\balena-etcher\resources\app\generated\child-writer.js
gui.js:37 Error: Error invoking remote method 'disable-screensaver': No handler registered for 'disable-screensaver'
    at o.invoke (node:electron/js2c/renderer_init:57:526)

gui.js:37 Error: User did not grant permission.
    at gui.js:37:773107
    at ChildProcess.exithandler (node:child_process:415:5)
    at ChildProcess.emit (node:events:526:28)
    at maybeClose (node:internal/child_process:1092:16)
    at ChildProcess._handle.onexit (node:internal/child_process:302:5)
(anonymous) @ gui.js:37
gui.js:35  0 devices, 0% at 0.00 MB/s (total 0.00 MB/s)  with 0 failed devices
gui.js:37 Error: Error invoking remote method 'enable-screensaver': No handler registered for 'enable-screensaver'
    at o.invoke (node:electron/js2c/renderer_init:57:526)

**Comment by bpyrih** [comment]
Same here
![image](https://github.com/balena-io/etcher/assets/112889330/ffa11752-c708-4d9a-91b5-b225571c8890)
