### ISSUE TITLE
Source and destination checksums do not match for Armbian XZ image

### ISSUE THREAD

**Issue by sibest19** [balena-io/etcher#4280]
- **Etcher version:** 1.19.21
- **Operating system and architecture:** macOS 14.4.1 (23E224) - Apple M1 Max
- **Image flashed:** [Armbian_24.5.1_Bananapim5_noble_current_6.6.31_gnome-oibaf_desktop.img.xz](https://dl.armbian.com/bananapim5/archive/Armbian_24.5.1_Bananapim5_noble_current_6.6.31_gnome-oibaf_desktop.img.xz)
- **Expected behavior:** The verification process should complete successfully after writing the image.
- **Actual behavior:** The writer process ended unexpectedly.

**Meaningful error information in the DevTools:**
```json
{
  "name": "Error",
  "message": "Source and destination checksums do not match: c047be3815d606d9 !== 53eb5d7ebb79041b",
  "stack": "Error: Source and destination checksums do not match: c047be3815d606d9 !== 53eb5d7ebb79041b\n    at CountingHashStream.<anonymous> (/snapshot/Users/runner/work/etcher/etcher/node_modules/etcher-sdk/build/source-destination/source-destination.js:158:36)\n    at CountingHashStream.emit (node:events:518:28)\n    at CountingHashStream.<anonymous> (/snapshot/Users/runner/work/etcher/etcher/node_modules/etcher-sdk/build/source-destination/source-destination.js:78:16)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)",
  "code": "EVALIDATION"
}
```

```
Error: The writer process ended unexpectedly
    at i (index.js:353:5238)
    at t.createUserError (index.js:353:6464)
    at m (index.js:140:45502)
    at index.js:140:46208
    at L.<anonymous> (index.js:140:42787)
    at L.emit (node:events:518:28)
    at e.exports.H (index.js:2:2317562)
    at e.exports.emit (node:events:518:28)
    at index.js:2:2293382
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Additional Information:**
- I attempted the same image with a different Mac (Intel) running the same version of Balena Etcher on macOS 13.*.
- Tried using both external and internal card readers.
- Used a newly-bought SD card.
- Verified the SHA256 sum of the image to ensure it wasn't corrupted against [this checksum](https://dl.armbian.com/bananapim5/archive/Armbian_24.5.1_Bananapim5_noble_current_6.6.31_gnome-oibaf_desktop.img.xz.sha).

My educated guess is that there may be an issue with this specific image. Any help or guidance on this would be greatly appreciated! 🙏

Thank you for your support!

**Comment by fakhir** [comment]
I faced this problem for an image which was a multiple of 512 but not a multiple of 1024 bytes. So I resized the image to make it a multiple of 4 MiB and that fixed the problem for me.
