### ISSUE TITLE
index.js:2 TypeError: (0 , h.requestMetadata) is not a function

### ISSUE THREAD

**Issue by sctech-tr** [balena-io/etcher#4324]
- **Etcher version:** 1.19.21 installed via RPM package
- **Operating system and architecture:** Fedora Linux 40 x64 (KDE Plasma)
- **Image flashed:** Slax Linux's latest version, i modified the bootscreen and packed it again. it still fails at the normal iso too
- **What do you think should have happened:** i wanted it to etch my iso
- **What happened:** it gave this error about non-functional functions (get it?)
![image](https://github.com/user-attachments/assets/79778668-2e8c-4013-bd50-5d1b0f9bc82a)
- **Do you see any meaningful error information in the DevTools?** 
this:  
index.js:2 TypeError: (0 , h.requestMetadata) is not a function
at index.js:140:1512
at async W.openImageSelector (index.js:140:2626)

**Comment by sivendsg** [comment]
i am having the same problom adn i dont know how to fix it someone help

**Comment by sctech-tr** [comment]
use something like unetbootin or rufus until it gets fixed
https://rufus.ie
https://unetbootin.github.io

**Comment by lurch** [comment]
Probably a duplicate of #4150 ?

**Comment by SamuelBanya** [comment]
Everyone, use an older version of the AppImage release like Version 1.13.0 found on this release page:
- https://github.com/balena-io/etcher/releases?page=5

**Comment by sctech-tr** [comment]
Duplicate of #4150

**Comment by rglidden** [comment]
@sctech-tr A fix for the .rpm package was merged into 1.19.24 today and is working on my Fedora 40 install. Can you give that version a try? https://github.com/balena-io/etcher/releases/tag/v1.19.24
