### ISSUE TITLE
"Error spawning the child process" upon flashing

### ISSUE THREAD

**Issue by fatso83** [balena-io/etcher#4356]
- **Etcher version:**  1.19.25
- **Operating system and architecture:** macOS 15, arm64 Apple M2 Max
- **Image flashed:** ubuntu-24.04.1-live-server-amd64.iso
- **What do you think should have happened:** 
Not get an error message without any logs to go by

1. Select the image
2. Select the USB device (tried both 8GB and 64GB sticks)
3. Flash
4. Success? (got error instead: "Error spawning the child process")

- **What happened:**
"Error spawning the child process" which is caused by a swallowed process exception:
```
"Error: Elevation timeout\n    at file:///Applications/balenaEtcher.app/Contents/Resources/app.asar/.webpack/renderer/main_window/index.js:355:4465\n    at r (file:///Applications/balenaEtcher.app/Contents/Resources/app.asar/.webpack/renderer/main_window/index.js:2:329483)"
```

<img width="912" alt="Skjermbilde 2024-11-17 kl  11 33 16" src="https://github.com/user-attachments/assets/07d989a9-5a0e-4566-8b7d-9729c26f641e">

- **Do you see any meaningful error information in the DevTools?** 
<details>
<summary>Full log</summary>
index.js:2  _____ _       _
|  ___| |     | |
| |__ | |_ ___| |__   ___ _ __
|  __|| __/ __| '_ \ / _ \ '__|
| |___| || (__| | | |  __/ |
\____/ \__\___|_| |_|\___|_|

Interested in joining the Etcher team?
Drop us a line at join+etcher@balena.io

Version = 1.19.25, Type = local
index.js:140 Spawning unpriviledged sidecar on port 3434
index.js:2 Starting...
index.js:2 Starting...
index.js:2 Starting...
index.js:2 /Applications/balenaEtcher.app/Contents/Resources/etcher-util
index.js:2 etcher-l1y2og
index.js:2 Retrying to connect to child process in 1000... 1 / 10
index.js:2 Amplitude Logger [Warn]: {code: 0, error: "Status 'unknown' provided for 2 events"}
(anonymous) @ index.js:2
index.js:2 etcher-l1y2og
index.js:2 Amplitude Logger [Warn]: {code: 0, error: "Status 'unknown' provided for 1 events"}
(anonymous) @ index.js:2
index.js:2 CHILD READY
index.js:2 start heartbeat
index.js:2 CHILD LOG: Ready ...
index.js:2 CHILD LOG: Scan requested
index.js:2 Starting...
index.js:2 Starting...
index.js:2 Starting...
index.js:2 Amplitude Logger [Warn]: {code: 0, error: "Status 'unknown' provided for 3 events"}
(anonymous) @ index.js:2
index.js:2 Amplitude Logger [Warn]: {code: 0, error: "Status 'unknown' provided for 1 events"}
(anonymous) @ index.js:2
index.js:2 CHILD LOG: sourceMetadata requested
index.js:2 Starting...
index.js:2 Amplitude Logger [Warn]: {code: 0, error: "Status 'unknown' provided for 1 events"}
(anonymous) @ index.js:2
index.js:2 Amplitude Logger [Warn]: {code: 0, error: "Status 'unknown' provided for 4 events"}
(anonymous) @ index.js:2
index.js:2 Amplitude Logger [Warn]: {code: 0, error: "Status 'unknown' provided for 1 events"}
(anonymous) @ index.js:2
index.js:2 Starting...
index.js:2 Amplitude Logger [Warn]: {code: 0, error: "Status 'unknown' provided for 1 events"}
(anonymous) @ index.js:2
index.js:2 Starting...
index.js:2 Amplitude Logger [Warn]: {code: 0, error: "Status 'unknown' provided for 4 events"}
(anonymous) @ index.js:2
index.js:2 Starting...
index.js:2 Amplitude Logger [Warn]: {code: 0, error: "Status 'unknown' provided for 1 events"}
(anonymous) @ index.js:2
index.js:2 Starting...
index.js:2 Starting...
index.js:2 Starting...
index.js:2 Starting...
index.js:2 Spawning priviledged sidecar on port 3435
index.js:2 /Applications/balenaEtcher.app/Contents/Resources/etcher-util
index.js:2 ... with privileges ...
index.js:2 Starting...
index.js:2  0 devices, 0% at 0.00 MB/s (total 0.00 MB/s)  with 0 failed devices
index.js:2 Amplitude Logger [Warn]: {code: 0, error: "Status 'unknown' provided for 1 events"}
(anonymous) @ index.js:2
index.js:2 Amplitude Logger [Warn]: {code: 0, error: "Status 'unknown' provided for 1 events"}
(anonymous) @ index.js:2
index.js:2 Amplitude Logger [Warn]: {code: 0, error: "Status 'unknown' provided for 1 events"}
(anonymous) @ index.js:2
index.js:2 Amplitude Logger [Warn]: {code: 0, error: "Status 'unknown' provided for 1 events"}
(anonymous) @ index.js:2
index.js:2 Amplitude Logger [Warn]: {code: 0, error: "Status 'unknown' provided for 1 events"}
(anonymous) @ index.js:2
index.js:2 Amplitude Logger [Error]: Event rejected due to exceeded retry count
(anonymous) @ index.js:2
index.js:2 Error spawning child process Error: Invalid error title: undefined
    at Object.i [as createError] (index.js:353:5185)
    at index.js:355:2732
    at async t.withTmpFile (index.js:2:903000)
    at async t.elevateCommand (index.js:355:2235)
    at async t.spawnChildAndConnect (index.js:140:43289)
    at async f (index.js:140:45207)
    at async t.flash (index.js:140:47000)
    at async S (index.js:140:51638)
    at async E.tryFlash (index.js:140:53449)
(anonymous) @ index.js:2
index.js:2 Starting...
index.js:2 Error: Error spawning the child process
    at t.spawnChildAndConnect (index.js:140:44239)
    at async f (index.js:140:45207)
    at async t.flash (index.js:140:47000)
    at async S (index.js:140:51638)
    at async E.tryFlash (index.js:140:53449)
(anonymous) @ index.js:2
index.js:2 Starting...
index.js:2 Starting...
media/icon.png:1 
        
        
       Failed to load resource: net::ERR_FILE_NOT_FOUND
index.js:2 Amplitude Logger [Warn]: {code: 0, error: "Status 'unknown' provided for 1 events"}
(anonymous) @ index.js:2
index.js:2 Amplitude Logger [Warn]: {code: 0, error: "Status 'unknown' provided for 1 events"}
(anonymous) @ index.js:2
index.js:2 Amplitude Logger [Warn]: {code: 0, error: "Status 'unknown' provided for 1 events"}
(anonymous) @ index.js:2
index.js:2 Amplitude Logger [Warn]: {code: 0, error: "Status 'unknown' provided for 1 events"}
(anonymous) @ index.js:2
index.js:2 Starting...
index.js:2 Amplitude Logger [Warn]: {code: 0, error: "Status 'unknown' provided for 1 events"}
(anonymous) @ index.js:2
index.js:2 Amplitude Logger [Error]: Event rejected due to exceeded retry count
(anonymous) @ index.js:2
index.js:2 Amplitude Logger [Warn]: {code: 0, error: "Status 'unknown' provided for 1 events"}
(anonymous) @ index.js:2
index.js:2 Amplitude Logger [Warn]: {code: 0, error: "Status 'unknown' provided for 1 events"}
(anonymous) @ index.js:2
index.js:2 Amplitude Logger [Warn]: {code: 0, error: "Status 'unknown' provided for 1 events"}
(anonymous) @ index.js:2
index.js:2 Amplitude Logger [Warn]: {code: 0, error: "Status 'unknown' provided for 1 events"}
(anonymous) @ index.js:2
index.js:2 Amplitude Logger [Warn]: {code: 0, error: "Status 'unknown' provided for 1 events"}
(anonymous) @ index.js:2
index.js:2 Amplitude Logger [Error]: Event rejected due to exceeded retry count
(anonymous) @ index.js:2
index.js:2 Amplitude Logger [Warn]: {code: 0, error: "Status 'unknown' provided for 1 events"}
(anonymous) @ index.js:2
index.js:2 CHILD LOG: sourceMetadata requested
index.js:2 Starting...
index.js:2 Amplitude Logger [Warn]: {code: 0, error: "Status 'unknown' provided for 2 events"}
(anonymous) @ index.js:2
index.js:2 Amplitude Logger [Warn]: {code: 0, error: "Status 'unknown' provided for 1 events"}
(anonymous) @ index.js:2
index.js:2 Amplitude Logger [Warn]: {code: 0, error: "Status 'unknown' provided for 1 events"}
(anonymous) @ index.js:2
index.js:2 Amplitude Logger [Warn]: {code: 0, error: "Status 'unknown' provided for 1 events"}
(anonymous) @ index.js:2
index.js:2 Amplitude Logger [Warn]: {code: 0, error: "Status 'unknown' provided for 1 events"}
(anonymous) @ index.js:2
index.js:2 Amplitude Logger [Warn]: {code: 0, error: "Status 'unknown' provided for 1 events"}
(anonymous) @ index.js:2
e.warn @ index.js:2
e.handleResponse @ index.js:2
(anonymous) @ index.js:2
(anonymous) @ index.js:355
(anonymous) @ index.js:355
a @ index.js:355
Promise.then (async)
l @ index.js:355
(anonymous) @ index.js:355
h @ index.js:355
e.send @ index.js:2
(anonymous) @ index.js:2
(anonymous) @ index.js:2
(anonymous) @ index.js:355
(anonymous) @ index.js:355
(anonymous) @ index.js:355
h @ index.js:355
e.flush @ index.js:2
(anonymous) @ index.js:2
r @ index.js:2
index.js:2 Amplitude Logger [Warn]: {code: 0, error: "Status 'unknown' provided for 1 events"}
(anonymous) @ index.js:2
e.warn @ index.js:2
e.handleResponse @ index.js:2
(anonymous) @ index.js:2
(anonymous) @ index.js:355
(anonymous) @ index.js:355
a @ index.js:355
Promise.then (async)
l @ index.js:355
(anonymous) @ index.js:355
h @ index.js:355
e.send @ index.js:2
(anonymous) @ index.js:2
(anonymous) @ index.js:2
(anonymous) @ index.js:355
(anonymous) @ index.js:355
(anonymous) @ index.js:355
h @ index.js:355
e.flush @ index.js:2
(anonymous) @ index.js:2
r @ index.js:2
setTimeout (async)
(anonymous) @ index.js:2
e.schedule @ index.js:2
(anonymous) @ index.js:2
Promise.then (async)
(anonymous) @ index.js:2
r @ index.js:2
setTimeout (async)
(anonymous) @ index.js:2
e.schedule @ index.js:2
(anonymous) @ index.js:2
Promise.then (async)
(anonymous) @ index.js:2
r @ index.js:2
index.js:2 Amplitude Logger [Error]: Event rejected due to exceeded retry count
(anonymous) @ index.js:2
e.error @ index.js:2
(anonymous) @ index.js:2
(anonymous) @ index.js:355
(anonymous) @ index.js:355
a @ index.js:355
index.js:2 Amplitude Logger [Warn]: {code: 0, error: "Status 'unknown' provided for 1 events"}
(anonymous) @ index.js:2
e.warn @ index.js:2
e.handleResponse @ index.js:2
(anonymous) @ index.js:2
(anonymous) @ index.js:355
(anonymous) @ index.js:355
a @ index.js:355
Promise.then (async)
l @ index.js:355
(anonymous) @ index.js:355
h @ index.js:355
e.send @ index.js:2
(anonymous) @ index.js:2
(anonymous) @ index.js:2
(anonymous) @ index.js:355
(anonymous) @ index.js:355
(anonymous) @ index.js:355
h @ index.js:355
e.flush @ index.js:2
(anonymous) @ index.js:2
r @ index.js:2
setTimeout (async)
(anonymous) @ index.js:2
e.schedule @ index.js:2
(anonymous) @ index.js:2
Promise.then (async)
(anonymous) @ index.js:2
r @ index.js:2
setTimeout (async)
(anonymous) @ index.js:2
e.schedule @ index.js:2
(anonymous) @ index.js:2
Promise.then (async)
(anonymous) @ index.js:2
r @ index.js:2
setTimeout (async)
(anonymous) @ index.js:2
e.schedule @ index.js:2
(anonymous) @ index.js:2
Promise.then (async)
(anonymous) @ index.js:2
r @ index.js:2
index.js:2 Amplitude Logger [Error]: Event rejected due to exceeded retry count
(anonymous) @ index.js:2
e.error @ index.js:2
(anonymous) @ index.js:2
(anonymous) @ index.js:355
(anonymous) @ index.js:355
a @ index.js:355
</details>
<img width="868" alt="Skjermbilde 2024-11-17 kl  11 39 03" src="https://github.com/user-attachments/assets/4748685a-5dd4-4eb3-8a64-fbdb85a5f806">
<img width="868" alt="Skjermbilde 2024-11-17 kl  11 38 56" src="https://github.com/user-attachments/assets/67be7fcb-8399-40e1-90c4-84100a7c6020">

```
❯ npx envinfo --system

  System:
    OS: macOS 15.1
    CPU: (12) arm64 Apple M2 Max
    Memory: 154.95 MB / 64.00 GB
    Shell: 5.2.37 - /opt/homebrew/bin/bash
```

<img width="1624" alt="Skjermbilde 2024-11-17 kl  11 50 49" src="https://github.com/user-attachments/assets/4cd9f8e7-c264-4f8f-a37f-00bb7c53397d">
<img width="1624" alt="Skjermbilde 2024-11-17 kl  11 49 19" src="https://github.com/user-attachments/assets/dd437a36-b05f-4418-a860-b6f264d5b8c8">
<img width="1624" alt="Skjermbilde 2024-11-17 kl  11 49 09" src="https://github.com/user-attachments/assets/74e127d3-b54f-4b5b-854c-09459413e842">

**Comment by fatso83** [comment]
Captured some more details from devtools. Not sure if it helps much.

**Comment by sumitsharansatsangi** [comment]
I am also facing the same error. Tried with different iso filed , checked hashed sum , everything was correct, but still the same pop up. Tried with old iso which was worked on earlier version of Balena etcher, but still the same pop up

**Comment by khmseu** [comment]
Same here under Linux. I suspect an install bug:
```
$ sudo dpkg -i ~/Downloads/balena-etcher_1.19.25_amd64.deb 
Vormals nicht ausgewähltes Paket balena-etcher wird gewählt.
(Lese Datenbank ... 1424642 Dateien und Verzeichnisse sind derzeit installiert.)
Vorbereitung zum Entpacken von .../balena-etcher_1.19.25_amd64.deb ...
Entpacken von balena-etcher (1.19.25) ...
balena-etcher (1.19.25) wird eingerichtet ...
**chmod: Zugriff auf '/opt/balenaEtcher/chrome-sandbox' nicht möglich: Datei oder Verzeichnis nicht gefunden**
Trigger für desktop-file-utils (0.23-3ubuntu3) werden verarbeitet ...
Trigger für bamfdaemon (0.5.3+18.04.20180207.2-0ubuntu1) werden verarbeitet ...
Rebuilding /usr/share/applications/bamf-2.index...
Trigger für gnome-menus (3.13.3-11ubuntu2) werden verarbeitet ...
Trigger für mime-support (3.60ubuntu1) werden verarbeitet ...
$

```

**Comment by khmseu** [comment]
No, that seems to not be it:
```
$ grep chmod /var/lib/dpkg/info/balena-etcher.*
/var/lib/dpkg/info/balena-etcher.postinst:chmod 4755 '/opt/balenaEtcher/chrome-sandbox' || true
$ stat /usr/lib/balena-etcher/chrome-sandbox
  Datei: /usr/lib/balena-etcher/chrome-sandbox
  Größe: 54248     	Blöcke: 112        EA Block: 4096   Normale Datei
Gerät: fd00h/64768d	Inode: 10748261    Verknüpfungen: 1
Zugriff: (4755/-rwsr-xr-x)  Uid: (    0/    root)   Gid: (    0/    root)
Zugriff    : 2024-12-01 13:09:13.000000000 +0100
Modifiziert: 2024-10-10 11:51:14.000000000 +0200
Geändert   : 2024-12-01 13:09:37.241563640 +0100
 Geburt    : -
$ 

```
So, the install *is* buggy, but the mode of that file seems to be correct anyway.

**Comment by khmseu** [comment]
Balena seems to phone home **a lot**. I see these URLs:
```
          "url": "https://data.balena-cloud.com/amplitude/2/httpapi",
          "url": "https://efp.balena.io/?borderRight=false&darkBackground=true&etcher-version=1.19.25&api-version=2&optOutAnalytics=false"
```
Anyway, here's `$HOME/.config/balenaEtcher/sentry/scope_v3.json`, in case it helps someone - it's the only thing in there that looks vaguely like a log:
[scope_v3.json](https://github.com/user-attachments/files/17969132/scope_v3.json)

**Comment by djredflame** [comment]
Hi everyone,
I wanted to point out that the same issue occurs on Windows 10 (64-bit). I tried flashing a balena.img file using Balena Etcher, but it didn’t work, showing the same symptoms described in this issue.

Interestingly, I was able to flash the same balena.img successfully using Rufus. 

Best regards,
Dj Redflame

**Comment by henriIV-72** [comment]
with Balena-etcher 1.19.25: **same issue** when trying to flash
with Ubuntu 24.10 's default tool "startup disk crerator": USB is flashed **OK**

**in both cases, same HW:**
  System:
    OS: Linux 6.11 Ubuntu 24.10 24.10 (Oracular Oriole)
    CPU: (4) x64 Intel(R) Pentium(R) CPU  N3700  @ 1.60GHz
    Memory: 4.65 GB / 7.18 GB
    Container: Yes
    Shell: 5.2.32 - /bin/bash
