### ISSUE TITLE
Flashing fails on macOS Sequoia 15.2

### ISSUE THREAD

**Issue by bluemoehre** [balena-io/etcher#4364]
**Etcher version:**
1.19.25
 
**Operating system and architecture:**
macOS Sequoia 15.2 (Apple Silicon)
 
**Image flashed:**
LibreELEC-Generic.x86_64-12.0.1.img
 
**What do you think should have happened:** 
Flash should work

**What happened:**
Error at about 25%

**Do you see any meaningful error information in the DevTools?** 
> Error: The writer process ended unexpectedly
>     at i (index.js:353:5238)
>     at t.createUserError (index.js:353:6464)
>     at m (index.js:140:45502)

<img width="805" alt="Bildschirmfoto 2024-12-18 um 13 53 00" src="https://github.com/user-attachments/assets/46cf24ba-64ca-4256-bc43-2198b2feb6d3" />

**Comment by ghs** [comment]
I my case it just keeps on "Flashing..." and never finishes. Keeps showing ETA 26 minutes even after 2 hours passed.
